version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm i

  build:
    commands:
      - npx shadow-cljs release stockmaster

artifacts:
  files:
    - '**/*'
  base-directory: 'public'
